# Copyright (C) 2022 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/amazon/ford/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/amazon/ford/proprietary/etc/.tp/thermal.policy.conf:system/etc/.tp/thermal.policy.conf \
    vendor/amazon/ford/proprietary/lib/libcam.paramsmgr.so:system/lib/libcam.paramsmgr.so \
    vendor/amazon/ford/proprietary/lib/libcameracustom.so:system/lib/libcameracustom.so \
    vendor/amazon/ford/proprietary/vendor/smartvolume/ford/anlg_dock_headset.csv:system/vendor/smartvolume/ford/anlg_dock_headset.csv \
    vendor/amazon/ford/proprietary/vendor/smartvolume/ford/aux_digital.csv:system/vendor/smartvolume/ford/aux_digital.csv \
    vendor/amazon/ford/proprietary/vendor/smartvolume/ford/bt_a2dp.csv:system/vendor/smartvolume/ford/bt_a2dp.csv \
    vendor/amazon/ford/proprietary/vendor/smartvolume/ford/bt_a2dp_headphones.csv:system/vendor/smartvolume/ford/bt_a2dp_headphones.csv \
    vendor/amazon/ford/proprietary/vendor/smartvolume/ford/bt_a2dp_speaker.csv:system/vendor/smartvolume/ford/bt_a2dp_speaker.csv \
    vendor/amazon/ford/proprietary/vendor/smartvolume/ford/bt_sco.csv:system/vendor/smartvolume/ford/bt_sco.csv \
    vendor/amazon/ford/proprietary/vendor/smartvolume/ford/bt_sco_carkit.csv:system/vendor/smartvolume/ford/bt_sco_carkit.csv \
    vendor/amazon/ford/proprietary/vendor/smartvolume/ford/bt_sco_headset.csv:system/vendor/smartvolume/ford/bt_sco_headset.csv \
    vendor/amazon/ford/proprietary/vendor/smartvolume/ford/default.csv:system/vendor/smartvolume/ford/default.csv \
    vendor/amazon/ford/proprietary/vendor/smartvolume/ford/dgtl_dock_headeset.csv:system/vendor/smartvolume/ford/dgtl_dock_headeset.csv \
    vendor/amazon/ford/proprietary/vendor/smartvolume/ford/speaker.csv:system/vendor/smartvolume/ford/speaker.csv \
    vendor/amazon/ford/proprietary/vendor/smartvolume/ford/wired_headphone.csv:system/vendor/smartvolume/ford/wired_headphone.csv \
    vendor/amazon/ford/proprietary/vendor/smartvolume/ford/wired_headset.csv:system/vendor/smartvolume/ford/wired_headset.csv
